### ISSUE TITLE
auro-popover: interactive elements inside popover are focusable when hidden

### ISSUE THREAD

**Issue by geoffrich** [AlaskaAirlines/auro-popover#14]
## Describe the bug
Interactive elements elements inside a popover are focusable when hidden.

## To Reproduce
1. Go to the live [popover demo](https://auro.alaskaair.com/components/auro/popover#sticky-popovers)
2. Tab down to the sticky popover. Notice that you are able to tab to the button inside the sticky popover even when the popover is closed.

## Expected behavior
I am unable to tab to content inside of the popover when the popover is closed.

## Desktop (please complete the following information):
 - OS: Windows 10
 - Browser: Firefox
 - Version: 85

**Comment by blackfalcon** [comment]
This issue is tied to https://github.com/AlaskaAirlines/auro-popover/issues/10

**Comment by blackfalcon** [comment]
The resolution for this issue may be in the `inert` feature that @geoffrich recently completed with auro-interruption. 

Please see the last two PRs from @geoff https://github.com/AlaskaAirlines/auro-interruption/pulls?q=is%3Apr+is%3Aclosed

Please consult with @geoffrich for support in adding this functionality to the popover element.

**Comment by blackfalcon** [comment]
This issue will be addressed with other feature work in https://github.com/AlaskaAirlines/auro-popover/issues/20
