### ISSUE TITLE
auro-popover: trigger is null when used in Svelte

### ISSUE THREAD

**Issue by geoffrich** [AlaskaAirlines/auro-popover#28]
## Describe the bug
The following markup (copied from the doc site) throws an exception when used in a Svelte component:

```html
<auro-popover for="button1">
	Top popover content!
	<auro-button id="button1" slot="trigger">Popover Test</auro-button>
</auro-popover>
```

<details>
<summary>Stack trace</summary>

```
Uncaught (in promise) TypeError: this.trigger is null
    firstUpdated auro-popover.js:94
    performUpdate updating-element.js:572
    _enqueueUpdate updating-element.js:508
    requestUpdateInternal updating-element.js:474
    initialize updating-element.js:326
    initialize lit-element.js:150
    UpdatingElement updating-element.js:90
    LitElement lit-element.js:82
    AuroPopover auro-popover.js:26
    element index.mjs:208
    create bundle.js:5266
    init index.mjs:1510
    App bundle.js:5318
    app main.js:3
    <anonymous> bundle.js:5338
auro-popover.js:94:14
```

</details>

## To Reproduce
Render the above markup in a Svelte component. Notice that an exception is thrown and the popover does not appear on hover.

## Expected behavior
No exception is thrown and the popover appears on hover.

## Desktop (please complete the following information):
 - OS: Windows 10
 - Browser: Firefox

**Comment by Dayna-A** [comment]
@blackfalcon @geoffrich I am experiencing this same exception when attempting to use auro-popover in another auro-component with an icon as the trigger. 
```
<auro-popover for="plugIcon" removeSpace>
  Notice this popover is a little<br>closer to the trigger.
  <auro-icon id="plugIcon" category="in-flight" name="plug" slot="trigger" tabindex="0"></auro-icon>
</auro-popover>
```
Was a workaround ever found for svelte?

**Comment by geoffrich** [comment]
Looked into this a bit more, and found out that this only happens with `auro-button`. If you use a regular `button` as the trigger everything works.

```html
<auro-popover for="button1">
	Top popover content!
	<button id="button1" slot="trigger">Popover Test</button>
</auro-popover>
```

The underlying issue here is setting `id` on the auro-button. In general, Svelte will set the property on a custom element instead of the ID. So, `id` is set as a property. When auro-popover tries to query for the trigger using `document.querySelector`, nothing is returned because the `id` attribute is not set.

You can workaround this using a Svelte action as outlined in my [CSS-Tricks article](https://css-tricks.com/using-custom-elements-in-svelte/#using-a-svelte-action-to-force-setting-attributes) on this topic.

```svelte
<script>
	function setId(node, id) {
		node.setAttribute('id', id);
	}
</script>

<auro-popover for="button1">
	Top popover content!
	<auro-button use:setId={'button1'} slot="trigger">Popover Test</auro-button>
</auro-popover>
```

@blackfalcon @jason-capsule42 @gusnaughton do you know if it's necessary that we use `querySelector` here at all? Or will the trigger always be in the slot? If it's always in the slot, maybe there's an opportunity to programatically get the contents of the slot instead of forcing the user to define `for` and `id` attributes. That would simplify things for all involved.

For reference:
https://github.com/AlaskaAirlines/auro-popover/blob/4d58ca8b8b839a7b9d975d076e8d081cbac7a94a/src/auro-popover.js#L71-L75

**Comment by blackfalcon** [comment]
> ...do you know if it's necessary that we use querySelector here at all? Or will the trigger always be in the slot?

The trigger should always be in this slot.
