### ISSUE TITLE
auro-popover: sticky CLICK event

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/auro-popover#6]
# User story

As a user, I want to be able to open a popover on CLICK, so I can interact with content inside the popover.
See https://github.com/AlaskaAirlines/auro-dialog/pull/14 for discussion.

As a user on a mobile device, I want a popover to present itself in a mobile appropriate experience so that I am not distracted or annoyed by a desktop experience. 

## Outline subtasks or tasks

> List specific steps required to deliver this work.

- [ ] Update popover to use a CLICK event
- [ ] Enable via attribute

## Definition of “Done” (exit criteria)

This story will be considered complete once ...
* the user can enable a popover element by clicking on a trigger

#### Has been tested in all browsers

- [ ] Chrome
- [ ] Firefox
- [ ] Edge (79 +)
- [ ] Safari
- [ ] Mobile Safari

**Comment by blackfalcon** [comment]
[9:27 AM] Brent Labasan
What is the criteria for the popover disappearing? For my current 606028 https://dev.azure.com/itsals/E_Sell_Shop/_workitems/edit/606028 it seems like the criteria should be: if the user clicks on something other than the popover itself or the priceCell that was clicked on to show the popover.

[9:52 AM] Dale Sande
Right. IMHO, the popover should close when there is an action INSIDE the popover and could close if there is any action that happens OUTSIDE the popover. 

This would be the same for the dropdown component I am working on, a model you can see here https://shoelace.style/components/dropdown

Or... 

It could require the button to be clicked again to close if there was no action taken inside
https://shoelace.style/components/tooltip?id=click-trigger

See what Erika has to say about that.

**Comment by BrentLabasan** [comment]
I am currently working on this.
